# Generated by Django 4.2.13 on 2024-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_province_profile_address_profile_bank_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
