# Generated by Django 4.2.13 on 2024-08-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customfieldvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='custom_field',
        ),
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='profile',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='CustomFieldValue',
        ),
    ]
